[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
atomic = "true"
py_version=311

[tool.mypy]
python_version = "3.11"
exclude = [".venv"]

[tool.ruff]
line-length = 100
